# permissions for end users to view mariadbschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbschema-viewer-role
rules:
- apiGroups:
  - database.openstack.org
  resources:
  - mariadbschemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.openstack.org
  resources:
  - mariadbschemas/status
  verbs:
  - get
