# permissions for end users to view mariadbaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mariadbaccount-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mariadb-operator
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mariadbaccount-viewer-role
rules:
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts/status
  verbs:
  - get
