# permissions for end users to edit mariadbschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbschema-editor-role
rules:
- apiGroups:
  - database.openstack.org
  resources:
  - mariadbschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.openstack.org
  resources:
  - mariadbschemas/status
  verbs:
  - get
