---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbs/status
  verbs:
  - get
  - patch
  - update
