apiVersion: database.openstack.org/v1beta1
kind: MariaDBSchema
metadata:
  name: mariadbschema-sample
  labels:
    dbName: mariadb
spec:
  name: scott
  secret: tiger #the name of a k8s secret containing DatabasePassword
