apiVersion: mariadb.openstack.org/v1beta1
kind: MariaDBAccount
metadata:
  labels:
    app.kubernetes.io/name: mariadbaccount
    app.kubernetes.io/instance: mariadbaccount-sample
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mariadb-operator
  name: mariadbaccount-sample
spec:
  # TODO(user): Add fields here
