apiVersion: mariadb.openstack.org/v1beta1
kind: Galera
metadata:
  name: openstack
spec:
  secret: mariadb-secret
  storageClass: local-storage
  storageRequest: 500M
  containerImage: quay.io/podified-antelope-centos9/openstack-mariadb:current-podified
  replicas: 3
  customServiceConfig: |
    [mysqld]
    max_connections = 8192
